adminapp/urls.py
from . import views
from django.urls import path


app_name = 'adminapp'

urlpatterns = [
    path('index',views.index,name="index"),
    path('agent',views.agent,name="agent"),
    path('add-agent',views.add_agent,name="add_agent"),
    path('view-agent',views.view_agent,name="view_agent"),
    path('edit-agent/<int:id>',views.edit_agent,name="edit_agent"),
    path('delete-agent/<int:id>',views.delete_agent,name="delete_agent"),
    path('ban-agent/<int:id>',views.ban_agent,name="ban_agent"),
    path('remove-ban/<int:id>',views.remove_ban,name="remove_ban"),
    path('package',views.package,name="package"),
    path('new-package',views.new_package,name="new_package"),
    path('edit-package/<int:id>',views.edit_package,name="edit_package"),
    path('delete-package/<int:id>',views.delete_package,name="delete_package"),
    path('add-result/<int:id>',views.add_result,name="add_result"),
    path('add-result-times',views.add_result_times,name="add_result_times"),
    path('republish-results/<int:id>',views.republish_results,name="republish_results"),
    path('result-times',views.republish_times,name="republish_times"),
    path('sales-report',views.sales_report,name="sales_report"),
    path('get-dealers/',views.get_dealers,name="get_dealers"),
    path('add-time',views.add_time,name="add_time"),
    path('change-time',views.change_time,name="change_time"),
    path('change-game-time/<int:id>',views.change_game_time,name="change_game_time"),
    path('monitor-times',views.monitor_times,name="monitor_times"),
    path('monitor/<int:id>',views.monitor,name="monitor"),
    path('set-monitor/<int:id>',views.set_monitor,name="set_monitor"),
    path('set-monitor-times',views.set_monitor_times,name="set_monitor_times"),
    path('dailyreport',views.daily_report,name="dailyreport"),
    path('countwise-report',views.countwise_report,name="countwise_report"),
    path('countsales-report',views.countsales_report,name="countsales_report"),
    path('winning_report',views.winning_report,name="winning_report"),
    path('winningcount-report',views.winningcount_report,name="winningcount_report"),
    path('blocked_numbers',views.blocked_numbers,name="blocked_numbers"),
    path('edit-bill-times',views.edit_bill_times,name="edit_bill_times"),
    path('edit_bill/<int:id>',views.edit_bill,name="edit_bill"),
    path('delete-bill/<int:id>',views.delete_bill,name="delete_bill"),
    path('deleting-bill/<int:id>',views.deleting_bill,name="deleting_bill"),
    path('deleting-row/<int:id>/<int:bill_id>',views.delete_row,name="deleting_row"),
    path('payment_report',views.payment_report,name="payment_report"),
    path('change_password',views.change_password,name="change_password"),
    path('view-results',views.view_results,name="view_results"),
    path('add-collection',views.add_collection,name="add_collection"),
    path('balance-report',views.balance_report,name="balance_report"),
    path('set-limit',views.set_limit,name="set_limit"),
    path('view-limit',views.view_limits,name="view_limits"),
    path('edit-limit/<int:id>',views.edit_limit,name="edit_limit"),
    path('blocked-number-times',views.blocked_number_times,name="blocked_number_times"),
    path('blocked-numbers/<int:id>',views.blocked_numbers,name="blocked_numbers"),
    path('new-block/<int:id>',views.new_block,name="new_block"),
    path('edit-block/<int:id>/<int:time_id>',views.edit_block,name="edit_block"),
    path('delete-block/<int:id>/<int:time_id>',views.delete_block,name="delete_block"),
    path('clear-limit/<int:id>/<int:time_id>',views.clear_limit,name="clear_limit"),
    path('clear-all/<int:id>',views.clear_all,name="clear_all"),
    path('settings',views.settings,name="settings"),
    path('lsk-limit/<int:id>',views.lsk_limit,name="lsk_limit"), 
    path('total-balance',views.total_balance,name="total_balance"),
    path('tickets-report',views.tickets_report,name="tickets_report"),
    path('position-wise-report',views.position_wise_report,name="position_wise_report"),
    path('fetch-sorted-data/<int:id>/',views.fetch_sorted_data,name="fetch_sorted_data")
]

agent/urls.py
from django.urls import path
from . import views

app_name = 'agent'

urlpatterns = [
    path("index",views.index,name='index'),
    path('add-dealer',views.add_dealer,name="add_dealer"), 
    path('view-dealer',views.view_dealer,name="view_dealer"),
    path('ban-dealer/<int:id>',views.ban_dealer,name="ban_dealer"),
    path('remove-ban/<int:id>',views.remove_ban,name="remove_ban"),
    path('remove-ban/<int:id>',views.remove_ban,name="remove_ban"),
    path('delete-dealer/<int:id>',views.delete_dealer,name="delete_dealer"),
    path('edit-dealer/<int:id>',views.edit_dealer,name="edit_dealer"),
    path('Results',views.results,name="results"),

    path('booking',views.booking,name="booking"), 
    path('sales-report',views.sales_report,name="sales_report"), 
    path('daily-report',views.daily_report,name="daily_report"), 
    path('winning-report',views.winning_report,name="winning_report"),
    path('count-salesreport',views.count_salereport,name="count_salereport"),
    path('winning_countreport',views.winning_countreport,name="winning_countreport"),
    path('collection-report',views.payment_report,name="collection_report"),
    path('add-collection',views.add_collection,name="add_collection"),
    path('balance-report',views.balance_report,name="balance_report"),
    path('edit-bill-times',views.edit_bill_times,name="edit_bill_times"),
    path('edit-bill/<int:id>',views.edit_bill,name="edit_bill"),

    path('play-game/<int:id>',views.play_game,name="play_game"),

    path('package',views.package,name="package"),
    path('new-package',views.new_package,name="new_package"),
    path('edit-package/<int:id>',views.edit_package,name="edit_package"),
    path('delete-package/<int:id>',views.delete_package,name="delete_package"),
    path('check-limit/',views.check_limit, name='check_limit'),
    path('save-data/',views.save_data,name="save_data"),

    path('delete-test-row/<str:id>/',views.agent_game_test_delete,name="agent_game_test_delete"),
    path('update-test-row/<str:id>',views.agent_game_test_update,name="agent_game_test_update"),

    path('delete-bill/<int:id>',views.delete_bill,name="delete_bill"),
    path('deleting-bill/<int:id>',views.deleting_bill,name="deleting_bill"),
    path('deleting-row/<int:id>/<int:bill_id>',views.delete_row,name="deleting_row"),


    path('set-limit',views.set_limit,name="set_limit"),
    path('view-limit',views.view_limits,name="view_limits"),
    path('edit-limit/<int:id>',views.edit_limit,name="edit_limit"),
    path('change-password',views.change_password,name="change_password"),
    path('total-balance',views.total_balance,name="total_balance"),



]

guessmaster/urls.py
from django.contrib import admin
from django.urls import URLPattern, path, include
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path('adminapp/',include('adminapp.urls')),
    path('',include('website.urls')),
    path('agent/',include('agent.urls')),
    path('dealer/',include('dealer.urls')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/urls.py
from . import views
from django.urls import path

app_name = 'website'

urlpatterns = [
    path('login',views.login,name="login"),
    path('logout',views.logout_view,name="logout"),
    path('',views.lock,name="lock")
]

adminapp/views.py
import datetime
from django.shortcuts import render,redirect,get_object_or_404
from django.contrib.auth.decorators import login_required
from website.decorators import dealer_required, agent_required, admin_required
from website.forms import LoginForm,UserUpdateForm
from website.forms import AgentRegistration
from website.models import User,Agent,Dealer
from agent.models import AgentGame, DealerPackage
from dealer.models import DealerGame
from .models import PlayTime, AgentPackage, Result, Winning, CollectionReport, Monitor, CombinedGame, Limit, BlockedNumber, GameLimit
from django.contrib import messages
from django.views.decorators.csrf import csrf_exempt
from pytz import timezone as pytz_timezone
import pytz
from django.utils import timezone
from agent.models import Bill
from django.db.models import Q
import itertools
from django.db.models import Sum, F, DecimalField
from django.db.models.functions import Coalesce
from collections import defaultdict
from django.contrib.auth.forms import AdminPasswordChangeForm
from django.http import JsonResponse
from django.contrib.auth.forms import AdminPasswordChangeForm,SetPasswordForm
from django.contrib.auth.forms import AdminPasswordChangeForm,PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from itertools import chain
from django.db.models import Value, CharField, ExpressionWrapper, F
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph
from django.http import HttpResponse
from reportlab.lib.styles import ParagraphStyle
from reportlab.platypus import Paragraph, Spacer
from django.core.serializers import serialize
from django.core.serializers.json import DjangoJSONEncoder
from django.http import JsonResponse
import json

# Create your views here.

@admin_required
@login_required
def index(request):
    agent_count = Agent.objects.all().count()
    dealer_count = Dealer.objects.all().count()
   

    context = {
        
        'agent_count':agent_count,
        'dealer_count':dealer_count
    }
    return render(request,'adminapp/index.html', context)

def agent(request):
    return render(request,'adminapp/customer/agent.html')

@login_required
@admin_required
@csrf_exempt
def add_agent(request):
    login_form = LoginForm()
    agent_form = AgentRegistration()
    if request.method == "POST":
        agent_form = AgentRegistration(request.POST)
        login_form = LoginForm(request.POST)
        print(agent_form)
        print(login_form)
        if login_form.is_valid() and agent_form.is_valid():
            print("loginform is not working")
            user = login_form.save(commit=False)
            user.is_agent = True
            user.save()
            c = agent_form.save(commit=False)
            c.user = user
            c.save()
            messages.info(request, "Agent Created Successfully")
            return redirect("adminapp:new_package")
    return render(request,'adminapp/add_agent.html',{"login_form": login_form, "agent_form": agent_form})

@login_required
@admin_required
def view_agent(request):
    agents = Agent.objects.filter().all()
    packages = AgentPackage.objects.filter().all()
    context = {
        'agents' : agents,
        'packages' : packages
    }
    return render(request,'adminapp/view_agent.html',context)

@login_required
@admin_required
def view_limits(request):
    limits = Limit.objects.filter().all()
    context = {
        'limits' : limits
    }
    return render(request,'adminapp/view_limits.html',context)

@login_required
@admin_required
def edit_limit(request, id):
    times = PlayTime.objects.all().order_by('id')
    limit_instance = Limit.objects.get(id=id)

    if request.method == 'POST':
        limit = request.POST.get('limit')
        selected_times = request.POST.getlist('checkbox')
        selected_agent = request.POST.get('select-agent')

        # Update the daily_limit for the selected Limit
        limit_instance.daily_limit = limit
        limit_instance.save()

        # Update the checked_times for the selected Limit
        limit_instance.checked_times.set(selected_times)

        return redirect('adminapp:index')

    context = {
        'times': times,
        'limit_instance': limit_instance,
    }
    return render(request, 'adminapp/edit_limit.html', context)

@login_required
@admin_required
def edit_agent(request, id):
    agent = get_object_or_404(Agent, id=id)
    user = agent.user
   

    if request.method == 'POST':
        form = AdminPasswordChangeForm(user=user, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('adminapp:index')
    else:
        form = AdminPasswordChangeForm(user=user)

    return render(request, 'adminapp/edit_agent.html', {'form': form})

@login_required
@admin_required
def delete_agent(request,id):
    agent = get_object_or_404(Agent, id=id)
    agent_user = agent.user
    dealers = Dealer.objects.filter(agent=agent)
    try:
        for dealer in dealers:
            dealer_user = dealer.user
            dealer_user.delete()
    except:
        pass
    agent_user.delete()
    return redirect('adminapp:view_agent')

@login_required
@admin_required
def ban_agent(request,id):
    agent = get_object_or_404(Agent, id=id)
    user = agent.user
    user.is_active = False
    user.save()
    dealers = Dealer.objects.filter(agent=agent)
    try:
        for dealer in dealers:
            dealer_user = dealer.user
            dealer_user.is_active = False
            dealer_user.save()
            print(dealer_user.is_active)
    except:
        pass
    return redirect('adminapp:view_agent')

@login_required
@admin_required
def remove_ban(request,id):
    agent = get_object_or_404(Agent, id=id)
    user = agent.user
    user.is_active = True
    user.save()
    dealers = Dealer.objects.filter(agent=agent)
    try:
        for dealer in dealers:
            dealer_user = dealer.user
            dealer_user.is_active = True
            dealer_user.save()
            print(dealer_user.is_active)
    except:
        pass
    return redirect('adminapp:view_agent')

@login_required
@admin_required
def package(request):
    packages = AgentPackage.objects.filter().all()
    print(packages)
    context = {
        'packages' : packages
    }
    return render(request,'adminapp/package.html',context)

@login_required
@admin_required
def new_package(request):
    user_obj = request.user
    try:
        agent = Agent.objects.filter().all()
    except:
        pass
    if request.method == 'POST':
        agent_obj = request.POST.get('agent')
        package_name = request.POST.get('package_name')
        single_rate = request.POST.get('single_rate')
        single_dc = request.POST.get('single_dc')
        double_rate = request.POST.get('double_rate')
        double_dc = request.POST.get('double_dc')
        box_rate = request.POST.get('box_rate')
        box_dc = request.POST.get('box_dc')
        super_rate = request.POST.get('super_rate')
        super_dc = request.POST.get('super_dc')
        first_prize = request.POST.get('first_prize')
        first_dc = request.POST.get('first_dc')
        second_prize = request.POST.get('second_prize')
        second_dc = request.POST.get('second_dc')
        third_prize = request.POST.get('third_prize')
        third_dc = request.POST.get('third_dc')
        fourth_prize = request.POST.get('fourth_prize')
        fourth_dc = request.POST.get('fourth_dc')
        fifth_prize = request.POST.get('fifth_prize')
        fifth_dc = request.POST.get('fifth_dc')
        guarantee_prize = request.POST.get('guarantee_prize')
        guarantee_dc = request.POST.get('guarantee_dc')
        box_first_prize = request.POST.get('box_first_prize')
        box_first_prize_dc = request.POST.get('box_first_prize_dc')
        box_series_prize = request.POST.get('box_series_prize')
        box_series_dc = request.POST.get('box_series_dc')
        single1_prize = request.POST.get('single1_prize')
        single1_dc = request.POST.get('single1_dc')
        double2_prize = request.POST.get('double2_prize')
        double2_dc = request.POST.get('double2_dc')
        selected_agent = Agent.objects.get(id=agent_obj)
        if AgentPackage.objects.filter(agent=agent_obj).exists():
            messages.info(request, "Package is not set, This agent already have a package!")
        else:
            add_package = AgentPackage.objects.create(agent=selected_agent,created_by=user_obj,package_name=package_name,single_rate=single_rate,
                        single_dc=single_dc,double_rate=double_rate,double_dc=double_dc,box_rate=box_rate,
                        box_dc=box_dc,super_rate=super_rate,super_dc=super_dc,first_prize=first_prize,first_dc=first_dc,
                        second_prize=second_prize,second_dc=second_dc,third_prize=third_prize,third_dc=third_dc,fourth_prize=fourth_prize,
                        fourth_dc=fourth_dc,fifth_prize=fifth_prize,fifth_dc=fifth_dc,guarantee_prize=guarantee_prize,
                        guarantee_dc=guarantee_dc,box_first_prize=box_first_prize,box_first_prize_dc=box_first_prize_dc,
                        box_series_prize=box_series_prize,box_series_dc=box_series_dc,single1_prize=single1_prize,
                        single1_dc=single1_dc,double2_prize=double2_prize,double2_dc=double2_dc)
            add_package.save()
            messages.info(request, "Package created successfully!")
            return redirect('adminapp:set_limit')
    last_agent = Agent.objects.filter().last()
    print(last_agent.id)
    context = {
        'agents' : agent,
        'selected_agent' : last_agent.id,
    }
    return render(request,'adminapp/new_package.html',context)

@login_required

templates/adminapp/partials/base.html
{% load static %}
<!doctype html>
<html lang="en">


<!-- Mirrored from www.wrraptheme.com/templates/lucid/html/light/index7.html by HTTrack Website Copier/3.x [XR&CO'2014], Sat, 09 Sep 2023 12:05:13 GMT -->
<head>
<title>ADMIN</title>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge, chrome=1">
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
<meta name="description" content="Lucid Bootstrap 4.1.1 Admin Template">
<meta name="author" content="WrapTheme, design by: ThemeMakker.com">

<link rel="icon" href="{% static 'outgoing-call.png' %}" type="image/x-icon">


<link rel="stylesheet" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'vendor/font-awesome/css/font-awesome.min.css' %}">
<link rel="stylesheet" href="{% static 'vendor/chartist/css/chartist.min.css' %}">
<link rel="stylesheet" href="{% static 'vendor/chartist-plugin-tooltip/chartist-plugin-tooltip.css' %}">
<link rel="stylesheet" href="{% static 'vendor/jvectormap/jquery-jvectormap-2.0.3.min.css' %}"/>
<link rel="stylesheet" href="{% static 'vendor/jquery-datatable/dataTables.bootstrap4.min.css' %}">
<link rel="stylesheet" href="{% static 'vendor/jvectormap/jquery-jvectormap-2.0.3.min.css' %}">
<link rel="stylesheet" href="{% static 'vendor/morrisjs/morris.min.css' %}">

<link rel="stylesheet" href="{% static 'vendor/bootstrap-datepicker/css/bootstrap-datepicker3.min.css' %}">
<link rel="stylesheet" href="https://cdn.datatables.net/1.13.7/css/jquery.dataTables.min.css">
<link rel="stylesheet" href="hhttps://cdn.datatables.net/buttons/2.4.2/css/buttons.dataTables.min.css">

<!-- MAIN CSS -->
<link rel="stylesheet" href="{% static 'css/main.css' %}">
<link rel="stylesheet" href="{% static 'css/color_skins.css' %}">
  <!-- DataTables CSS -->
  <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.24/css/jquery.dataTables.min.css">
    



</head>
<body class="theme-cyan" style="background-color:rgb(213, 255, 205);">


<div id="wrapper">

    {% include 'adminapp/partials/header.html' %}
    {% include 'adminapp/partials/sidebar.html' %}

    {% block content %}

    {% endblock %}

</div>





<!-- Javascript -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.4.0/jspdf.umd.min.js"></script>


   <!-- jQuery -->
   <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    
   <!-- DataTables JS -->
   <script src="https://cdn.datatables.net/1.10.24/js/jquery.dataTables.min.js"></script>
   
   <!-- html2pdf.js -->
   <script src="https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.9.2/html2pdf.bundle.js"></script>
<!-- Include html2pdf library -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.9.2/html2pdf.bundle.js"></script>
<!-- Include html2pdf library -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.9.2/html2pdf.bundle.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.10.1/html2pdf.bundle.min.js" integrity="sha512-GsLlZN/3F2ErC5ifS5QtgpiJtWd43JWSuIgh7mbzZ8zBps+dvLusV+eNQATqgA/HdeKFVgA5v3S/cIrLF7QnIg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>



<script src="https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.10.1/html2pdf.bundle.min.js"></script>

<script src="{% static 'bundles/libscripts.bundle.js' %}"></script>    
<script src="{% static 'bundles/vendorscripts.bundle.js' %}"></script>

<script src="{% static 'bundles/jvectormap.bundle.js' %}"></script> <!-- JVectorMap Plugin Js -->
<script src="{% static 'bundles/chartist.bundle.js' %}"></script>
<script src="{% static 'bundles/datatablescripts.bundle.js' %}"></script>

<script src="{% static 'bundles/mainscripts.bundle.js' %}"></script>
<script src="{% static 'js/pages/tables/jquery-datatable.js' %}"></script>
<script src="{% static 'js/index7.js' %}"></script>
<script src="{% static 'js/widgets/infobox/infobox-1.js' %}"></script>
<script src="{% static 'js/index2.js' %}"></script>
<script src="{% static 'vendor/jquery-datatable/buttons/dataTables.buttons.min.js' %}"></script>
<script src="{% static 'vendor/jquery-datatable/buttons/buttons.bootstrap4.min.js' %}"></script>
<script src="{% static 'vendor/jquery-datatable/buttons/buttons.colVis.min.js' %}"></script>
<script src="{% static 'vendor/jquery-datatable/buttons/buttons.html5.min.js' %}"></script>
<script src="{% static 'vendor/jquery-datatable/buttons/buttons.print.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap-datepicker/js/bootstrap-datepicker.min.js' %}"></script>
<script src="{% static 'sweetalert/sweetalert.min.js' %}"></script> <!-- SweetAlert Plugin Js --> 

<script src="{% static 'vendor/editable-table/mindmup-editabletable.js' %}"></script>
<script src="{% static 'js/pages/tables/editable-table.js' %}"></script>

</body>

</html>

templates/adminapp/partials/header.html
{% load static %}
<nav class="navbar navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-btn">
            <button type="button" class="btn-toggle-offcanvas"><i class="lnr lnr-menu fa fa-bars"></i></button>
        </div>

        <div class="navbar-brand">
            <a href="{% url 'adminapp:index' %}"><img src="" class="img-responsive logo"></a>                
        </div>
        
        <div class="navbar-right">
        
        
        </div>
    </div>
</nav>

templates/adminapp/partials/sidebar.html
{% load static %}
<div id="left-sidebar" class="sidebar">
    <div class="sidebar-scroll">
        <div class="user-account">
            <div class="dropdown">
                <span>Welcome,</span>
                <a href="javascript:void(0);" class="dropdown-toggle user-name" data-toggle="dropdown"><strong>{{request.user}}</strong></a>
                <ul class="dropdown-menu dropdown-menu-right account">
                    <li><a href="{% url 'website:logout' %}"><i class="icon-power"></i>Logout</a></li>
                </ul>
            </div>
            <hr>
          
        </div>
        <!-- Nav tabs -->
        `
            
        <!-- Tab panes -->
        <div class="tab-content p-l-0 p-r-0">
            <div class="tab-pane active" id="menu">
                <nav id="left-sidebar-nav" class="sidebar-nav">
                    <ul id="main-menu" class="metismenu">                            
                        <li class="active">
                           
                                <a href="{% url 'adminapp:index' %}" ><i class="icon-home"></i> <span>Dashboard</span></a>
                               
                            </li>
                        <li>
                            <a href="#Results" class="has-arrow"><i class="icon-trophy"></i> <span>Result</span></a>
                            <ul>
                                <li><a href="{% url 'adminapp:add_result_times' %}">Add Result</a></li>                                    
                                <li><a href="{% url 'adminapp:republish_times' %}">Republish Result</a></li>
                                <li><a href="{% url 'adminapp:view_results' %}">View Results</a></li>  
                            </ul>
                        </li>
                        <li>
                            <a href="#Dashboard" class="has-arrow"><i class="icon-users"></i> <span>Agent</span></a>
                            <ul>
                                <li><a href="{% url 'adminapp:add_agent' %}">Add Agent</a></li>                                    
                                <li><a href="{% url 'adminapp:view_agent' %}">View Agent</a></li>
                                
                            </ul>
                        </li>
                        <li>
                            <a href="#Dashboard" class="has-arrow"><i class="icon-present"></i> <span>Package</span></a>
                            <ul>
                                <li><a href="{% url 'adminapp:package' %}">Package</a></li>                                    
                                <li><a href="{% url 'adminapp:new_package' %}">New Package</a></li>
                                
                            </ul>
                        </li>
                        <li>
                            <a href="#Limit" class="has-arrow"><i class="icon-bar-chart"></i> <span>Daily Limit</span></a>
                            <ul>
                                <li><a href="{% url 'adminapp:view_limits' %}">Edit Limit</a></li>                                    
                                <li><a href="{% url 'adminapp:set_limit' %}">Set Limit</a></li>
                                
                            </ul>
                        </li>
                        <li>
                            <a href="#GameTime" class="has-arrow"><i class=" icon-speedometer"></i> <span>Game Time</span></a>
                            <ul>
                                <!-- <li><a href="{% url 'adminapp:add_time' %}">Add Time</a></li>                                     -->
                                <li><a href="{% url 'adminapp:change_time' %}">Change Time</a></li>
                                
                            </ul>
                        </li>
                        <li>
                            <a href="{% url 'adminapp:blocked_number_times' %}"><i class=" icon-control-pause"></i> <span>Blocked Numbers</span></a>
                        </li>
                        <li>
                            <a href="{% url 'adminapp:monitor_times' %}" ><i class="icon-screen-desktop"></i> <span>Monitor</span></a>
                           
                        </li>
                        <li>
                            <a href="{% url 'adminapp:sales_report' %}" ><i class="icon-notebook"></i> <span>Sales Report</span></a>
                           
                        </li>
                        <li>
                            <a href="{% url 'adminapp:dailyreport' %} "><i class="icon-book-open "></i> <span>Daily Report</span></a>
                         
                        </li>
                        
                        <li>
                            <a href="#uiElements" class="has-arrow"><i class="icon-grid"></i> <span>Others</span></a>
                            <ul>
                                <li><a href="{% url 'adminapp:tickets_report' %}">Tickets Report</a></li>
                                <li><a href="{% url 'adminapp:countwise_report' %}">Count Wise Report</a></li>
                                <li><a href="{% url 'adminapp:countsales_report' %}">Count Sale Report</a></li>
                                <li><a href="{% url 'adminapp:winning_report' %}">Winning Report</a></li>
                                <li><a href="{% url 'adminapp:position_wise_report' %}">Position Wise Report</a></li>
                                <li><a href="{% url 'adminapp:winningcount_report' %}">Count Winning Report</a></li>                                   
                                <li><a href="{% url 'adminapp:payment_report' %}">Payment Report</a></li>
                                <li><a href="{% url 'adminapp:balance_report' %}">Balance Report</a></li>
                                
                           
                            </ul>
                        </li>
                        <li>
                            <a href="{% url 'adminapp:edit_bill_times' %}"><i class="icon-note"></i>Edit Bill</a>
                        </li>
                        <li>
                            <a href="{% url 'adminapp:total_balance' %} "><i class="icon-book-open "></i> <span>Total Balance</span></a>
                         
                        </li>
                        <li>
                            <a href="{% url 'adminapp:settings' %}" ><i class="icon-settings"></i> <span>Settings</span></a>
                           
                        </li>
                        <li>
                            <a href="{% url 'adminapp:change_password' %}" ><i class="icon-wrench"></i> <span>Change Password</span></a>
                           
                        </li>
                        
                        <li>
                            <a href="{% url 'adminapp:index' %}"><i class="icon-refresh"></i> <span>Refresh</span></a>
                        </li>
                        
                       
                     
                    </ul>
                </nav>
            </div>
              
        </div>          
    </div>
</div>