adminapp/urls.py
from . import views
from django.urls import path


app_name = 'adminapp'

urlpatterns = [
    path('index',views.index,name="index"),
    path('agent',views.agent,name="agent"),
    path('add-agent',views.add_agent,name="add_agent"),
    path('view-agent',views.view_agent,name="view_agent"),
    path('edit-agent/<int:id>',views.edit_agent,name="edit_agent"),
    path('delete-agent/<int:id>',views.delete_agent,name="delete_agent"),
    path('ban-agent/<int:id>',views.ban_agent,name="ban_agent"),
    path('remove-ban/<int:id>',views.remove_ban,name="remove_ban"),
    path('package',views.package,name="package"),
    path('new-package',views.new_package,name="new_package"),
    path('edit-package/<int:id>',views.edit_package,name="edit_package"),
    path('delete-package/<int:id>',views.delete_package,name="delete_package"),
    path('add-result/<int:id>',views.add_result,name="add_result"),
    path('add-result-times',views.add_result_times,name="add_result_times"),
    path('republish-results/<int:id>',views.republish_results,name="republish_results"),
    path('result-times',views.republish_times,name="republish_times"),
    path('sales-report',views.sales_report,name="sales_report"),
    path('get-dealers/',views.get_dealers,name="get_dealers"),
    path('add-time',views.add_time,name="add_time"),
    path('change-time',views.change_time,name="change_time"),
    path('change-game-time/<int:id>',views.change_game_time,name="change_game_time"),
    path('monitor-times',views.monitor_times,name="monitor_times"),
    path('monitor/<int:id>',views.monitor,name="monitor"),
    path('set-monitor/<int:id>',views.set_monitor,name="set_monitor"),
    path('set-monitor-times',views.set_monitor_times,name="set_monitor_times"),
    path('dailyreport',views.daily_report,name="dailyreport"),
    path('countwise-report',views.countwise_report,name="countwise_report"),
    path('countsales-report',views.countsales_report,name="countsales_report"),
    path('winning_report',views.winning_report,name="winning_report"),
    path('winningcount-report',views.winningcount_report,name="winningcount_report"),
    path('blocked_numbers',views.blocked_numbers,name="blocked_numbers"),
    path('edit-bill-times',views.edit_bill_times,name="edit_bill_times"),
    path('edit_bill/<int:id>',views.edit_bill,name="edit_bill"),
    path('delete-bill/<int:id>',views.delete_bill,name="delete_bill"),
    path('deleting-bill/<int:id>',views.deleting_bill,name="deleting_bill"),
    path('deleting-row/<int:id>/<int:bill_id>',views.delete_row,name="deleting_row"),
    path('payment_report',views.payment_report,name="payment_report"),
    path('change_password',views.change_password,name="change_password"),
    path('view-results',views.view_results,name="view_results"),
    path('add-collection',views.add_collection,name="add_collection"),
    path('balance-report',views.balance_report,name="balance_report"),
    path('set-limit',views.set_limit,name="set_limit"),
    path('view-limit',views.view_limits,name="view_limits"),
    path('edit-limit/<int:id>',views.edit_limit,name="edit_limit"),
    path('blocked-number-times',views.blocked_number_times,name="blocked_number_times"),
    path('blocked-numbers/<int:id>',views.blocked_numbers,name="blocked_numbers"),
    path('new-block/<int:id>',views.new_block,name="new_block"),
    path('edit-block/<int:id>/<int:time_id>',views.edit_block,name="edit_block"),
    path('delete-block/<int:id>/<int:time_id>',views.delete_block,name="delete_block"),
    path('clear-limit/<int:id>/<int:time_id>',views.clear_limit,name="clear_limit"),
    path('clear-all/<int:id>',views.clear_all,name="clear_all"),
    path('settings',views.settings,name="settings"),
    path('lsk-limit/<int:id>',views.lsk_limit,name="lsk_limit"), 
    path('total-balance',views.total_balance,name="total_balance"),
    path('tickets-report',views.tickets_report,name="tickets_report"),
    path('position-wise-report',views.position_wise_report,name="position_wise_report"),
    path('fetch-sorted-data/<int:id>/',views.fetch_sorted_data,name="fetch_sorted_data")
]

agent/urls.py
from django.urls import path
from . import views

app_name = 'agent'

urlpatterns = [
    path("index",views.index,name='index'),
    path('add-dealer',views.add_dealer,name="add_dealer"), 
    path('view-dealer',views.view_dealer,name="view_dealer"),
    path('ban-dealer/<int:id>',views.ban_dealer,name="ban_dealer"),
    path('remove-ban/<int:id>',views.remove_ban,name="remove_ban"),
    path('remove-ban/<int:id>',views.remove_ban,name="remove_ban"),
    path('delete-dealer/<int:id>',views.delete_dealer,name="delete_dealer"),
    path('edit-dealer/<int:id>',views.edit_dealer,name="edit_dealer"),
    path('Results',views.results,name="results"),

    path('booking',views.booking,name="booking"), 
    path('sales-report',views.sales_report,name="sales_report"), 
    path('daily-report',views.daily_report,name="daily_report"), 
    path('winning-report',views.winning_report,name="winning_report"),
    path('count-salesreport',views.count_salereport,name="count_salereport"),
    path('winning_countreport',views.winning_countreport,name="winning_countreport"),
    path('collection-report',views.payment_report,name="collection_report"),
    path('add-collection',views.add_collection,name="add_collection"),
    path('balance-report',views.balance_report,name="balance_report"),
    path('edit-bill-times',views.edit_bill_times,name="edit_bill_times"),
    path('edit-bill/<int:id>',views.edit_bill,name="edit_bill"),

    path('play-game/<int:id>',views.play_game,name="play_game"),

    path('package',views.package,name="package"),
    path('new-package',views.new_package,name="new_package"),
    path('edit-package/<int:id>',views.edit_package,name="edit_package"),
    path('delete-package/<int:id>',views.delete_package,name="delete_package"),
    path('check-limit/',views.check_limit, name='check_limit'),
    path('save-data/',views.save_data,name="save_data"),

    path('delete-test-row/<str:id>/',views.agent_game_test_delete,name="agent_game_test_delete"),
    path('update-test-row/<str:id>',views.agent_game_test_update,name="agent_game_test_update"),

    path('delete-bill/<int:id>',views.delete_bill,name="delete_bill"),
    path('deleting-bill/<int:id>',views.deleting_bill,name="deleting_bill"),
    path('deleting-row/<int:id>/<int:bill_id>',views.delete_row,name="deleting_row"),


    path('set-limit',views.set_limit,name="set_limit"),
    path('view-limit',views.view_limits,name="view_limits"),
    path('edit-limit/<int:id>',views.edit_limit,name="edit_limit"),
    path('change-password',views.change_password,name="change_password"),
    path('total-balance',views.total_balance,name="total_balance"),



]

dealer/urls.py
from django.urls import path
from . import views


app_name = 'dealer'

urlpatterns = [

    path("index",views.index,name='index'),
    path('booking',views.booking,name="booking"), 
    path('result',views.result,name="result"), 
    path('edit-bill',views.edit_bill,name="edit_bill"),
    path('sales-report',views.sales_report,name="sales_report"),
    path('daily-report',views.daily_report,name="daily_report"), 
    path('winning-report',views.winning_report,name="winning_report"),
    path('count-salesreport',views.count_salereport,name="count_salereport"),
    path('winning_countreport',views.winning_countreport,name="winning_countreport"),
    path('balance-report',views.balance_report,name="balance_report"),
    path('play-game/<int:id>',views.play_game,name="play_game"),
    path('check-limit/',views.check_limit,name="check_limit"),
    path('save-data/',views.save_data,name="save_data"),
    path('edit-bill-times',views.edit_bill_times,name="edit_bill_times"),
    path('edit-bill/<int:id>',views.edit_bill,name="edit_bill"),
    path('delete-bill/<int:id>',views.delete_bill,name="delete_bill"),
    path('deleting-bill/<int:id>',views.deleting_bill,name="deleting_bill"),
    path('change-password',views.change_password,name="change_password"),
    path('deleting-row/<int:id>/<int:bill_id>',views.delete_row,name="deleting_row"),

    path('delete-test-row/<str:id>/',views.dealer_game_test_delete,name="dealer_game_test_delete"),
    path('update-test-row/<str:id>',views.dealer_game_test_update,name="dealer_game_test_update"),

]

guessmaster/urls.py
from django.contrib import admin
from django.urls import URLPattern, path, include
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path('adminapp/',include('adminapp.urls')),
    path('',include('website.urls')),
    path('agent/',include('agent.urls')),
    path('dealer/',include('dealer.urls')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dealer/models.py
from django.db import models
from agent.models import Agent,Dealer
from adminapp.models import PlayTime

# Create your models here.

class DealerGameTest(models.Model):
    agent = models.ForeignKey(Agent,on_delete=models.CASCADE,null=True, related_name='agent_dealergametests')
    created_by = models.ForeignKey(Agent,on_delete=models.CASCADE,null=True)
    customer = models.CharField(max_length=100,null=True)
    dealer = models.ForeignKey(Dealer,on_delete=models.CASCADE,null=True)
    time = models.ForeignKey(PlayTime,on_delete=models.CASCADE,null=True)
    date = models.DateField(auto_now_add=True)
    LSK = models.CharField(max_length=100)
    number = models.CharField(max_length=100)
    count = models.IntegerField()
    d_amount = models.FloatField()
    c_amount = models.FloatField()
    d_amount_admin = models.FloatField()
    c_amount_admin = models.FloatField()

    def __str__(self):
        return str(self.dealer)
    
class DealerGame(models.Model):
    agent = models.ForeignKey(Agent,on_delete=models.CASCADE,null=True)
    dealer = models.ForeignKey(Dealer,on_delete=models.CASCADE,null=True)
    customer = models.CharField(max_length=100,null=True)
    time = models.ForeignKey(PlayTime,on_delete=models.CASCADE,null=True)
    date = models.DateField(auto_now_add=True)
    LSK = models.CharField(max_length=100)
    number = models.CharField(max_length=100)
    count = models.IntegerField()
    d_amount = models.FloatField()
    c_amount = models.FloatField()
    d_amount_admin = models.FloatField()
    c_amount_admin = models.FloatField()
    combined = models.BooleanField()

    def __str__(self):
        return str(self.dealer)

templates/dealer/balance_report.html
{% extends 'dealer/partials/base.html' %}
{% load static %}
{% block content %}

<style>
    .navbar-bottom {
        position: fixed;
        bottom: 0;
        width: 100%;
        height: 55px;
        box-shadow: 0 0 10px rgba(0,0,0,0.2);
        background-color: #ffffff;
        overflow-x: auto;
        justify-content: space-evenly;
        display: flex;
        flex-direction: column;
    }

    .th{
        text-align: center;
    }

    .td2{
        text-align: center;
    }
    .td3{
        text-align: center;
    }
    .th1, .td1{
        text-align: center;
    }

 
</style>
<div id="main-content">
    <div class="container-fluid">
        <div class="block-header">
            <div class="row header">
                <div class="col-lg-12 col-md-12 col-sm-12">                        
                    <ul class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{% url 'adminapp:index' %}"><i class="icon-home"></i></a></li>                            
                        <li class="breadcrumb-item">Balance Report</li>
                        
                    </ul>
                </div> 
                
                    
               
            </div>
        </div>

        <div class="row clearfix" style="padding-left: 0px;padding-right: 0px;">
            <form method="POST">
                
                {% csrf_token %}
            <div class="col-lg-12 col-md-12 col-sm-12" >
                    <div class="body">
                        <div class="col-lg-12">
                            <div class="card  serch"  style="padding-left: 10px;padding-right: 10px;background-color:antiquewhite;padding-top: 10px;">
                                
                                <div class="body">
                                    <div class="row clearfix">
                                        <div class="col-md-6 col-6">
                                            <div class="form-group">
                                                <input type="date" class="form-control" id="from-date" name="from-date">
                                            </div>
                                        </div>
                                        <div class="col-md-6 col-6">
                                            <div class="form-group">
                                                <input type="date" class="form-control" id="to-date" name="to-date">
                                            </div>
                                        </div>
                                        
                                        
                                    <div class="col-md-6 col-6">
                                        <div class="form-group">                                               
                                                <button type="submit" class="btn btn-primary">Search</button>
                                            </div>
                                        </div>
                                        <div class="col-lg-2 col-md-6 col-6">
                                            <div class="form-group">
                                                <button class="btn btn-primary" id="pdfButton" name="pdfButton" type="submit">Download</button>

                                            </div>
                                        </div>
                                    
                                    </div>
                                                                        
                                    </div>
                                   
                                 </div>
                                
                              
                                   
                                </div>
                                
                            
                           
                        </div>
                    </div>
                    </div>
                </div>
            </div>
        </form>
        </div>
        <div class="body">
            <div class="table-responsive">
                <table class="table m-b-0">
                   
                    <thead class="l-blue">
                        <tr>
                            <th class="th">Date</th>
                            <th class="th">Sales<br>Amount</th>
                            <th class="th">Win<br>Amount</th>
                            <th class="th">Collection<br>Amount</th>
                            <th class="th">Balance</th>   
                        </tr>
                    </thead>
                    <tbody class="not-summary l-blush">
                        {% for data in report_data %}
                        <tr>
                            <td class="td2">{{data.date}}</td>
                            <td class="td2">{{data.total_d_amount|floatformat:2}}</td>
                            <td class="td2">{{data.win_amount|floatformat:2}}</td>
                            <td class="td3">{{data.from_or_to|floatformat:2}}</td>   
                            <td class="td2">{{data.balance|floatformat:2}}</td>                                              
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
               
            </div>
            <div  style="padding-top: 50px;"></div>
          
            </div>
        
    </div>
</div>

<nav class="navbar-bottom" id="btotal">
    <table>
        <thead>
            <tr>
                {% if total_balance|default:0|add:0 >= 0 %}
                <th class="th1" style="color: rgb(0, 192, 0);">Balance</th>
                {% else %}
                <th class="th1" style="color: red;">Balance</th>
                {% endif %}
            </tr>
        </thead>
        <tbody>
            <tr>
                {% if total_balance|default:0|add:0 >= 0 %}
                <td class="td1" style="color: rgb(0, 192, 0);">{{total_balance|floatformat:2}}</td>
                {% else %}
                <td class="td1" style="color: red;">{{total_balance|floatformat:2}}</td>
                {% endif %}
            </tr>
        </tbody>
    </table>
</nav>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    $(document).ready(function() {
        $("#expand-button").change(function() {
            if (this.checked) {
                $(".expand-row").show(); // Show the row when the checkbox is checked
            } else {
                $(".expand-row").hide(); // Hide the row when the checkbox is unchecked
            }
        });
    });
</script>

<script>
    // Get the current date in the format "YYYY-MM-DD"
    function getCurrentDate() {
        const now = new Date();
        const year = now.getFullYear();
        const month = (now.getMonth() + 1).toString().padStart(2, '0');
        const day = now.getDate().toString().padStart(2, '0');
        return `${year}-${month}-${day}`;
    }

    // Check if selected_from and selected_to are defined
    var selectedFrom = "{{selected_from}}";
    var selectedTo = "{{selected_to}}";

    if (selectedFrom && selectedTo) {
        document.getElementById('from-date').value = selectedFrom;
        document.getElementById('to-date').value = selectedTo;
    } else {
        document.getElementById('from-date').value = getCurrentDate();
        document.getElementById('to-date').value = getCurrentDate();
    }
</script>

<script>
    document.addEventListener("DOMContentLoaded", function () {
        var selectTime = document.getElementById("collection");
        selectTime.value = "{{ selected_time }}";

    });

    
</script>


<script>

    const x = document.getElementById("from-date");
    const y = document.getElementById("to-date");

    let currentVal = x.value;
    let currentValue = y.value;

    const daysOfWeek = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'];

    let fromDate = new Date(currentVal);
    let toDate = new Date(currentValue);

    let fromDayOfWeek = daysOfWeek[fromDate.getDay()];
    let toDayOfWeek = daysOfWeek[toDate.getDay()];

    document.getElementById("demo").innerHTML = " : " + currentVal + " (" + fromDayOfWeek + ")";
    document.getElementById("demo1").innerHTML = "&nbsp; to &nbsp;" + currentValue + " (" + toDayOfWeek + ")";



</script>

<script>
    //   pdftab hide

    document.addEventListener("DOMContentLoaded", function () {
        // Hide the pdftab div when the page loads
        var pdftab = document.getElementById("pdftab");
        if (pdftab) {
            pdftab.style.display = "none";
        }
    });
</script>

<script src="https://rawgit.com/eKoopmans/html2pdf/master/dist/html2pdf.bundle.js"></script>


{% endblock %} 

templates/dealer/change_password.html
{% extends 'agent/partials/base.html' %}

{% load static %}
{% block content %}

<style>

    .helptext{
      visibility: hidden;
    }
    
    </style>
<div id="main-content">
    <div class="container-fluid">
        <div class="block-header">
            <div class="row">
                <div class="col-lg-5 col-md-8 col-sm-12">
                    <h2><a href="javascript:void(0);" class="btn btn-xs btn-link btn-toggle-fullwidth"><i
                                class="fa fa-arrow-left"></i></a> Change Password</h2>
                    <ul class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{% url 'dealer:index' %}"><i class="icon-home"></i></a></li>
                        <li class="breadcrumb-item">Change Password</li>
                    </ul>
                </div>

            </div>
        </div>
        <div class="row clearfix">
            <div class="col-lg-12 col-md-12 col-sm-12">
                <div id="wrapper text-center">
                    <div class="vertical-align-wrap">
                        <div class="auth-box">
                            <div class="top">
                            </div>
                            <div class="card" style="background-color: antiquewhite;">
                                <div class="header">
                                    <p class="lead" style="font-weight: bolder;">Change Password</p>
                                </div>
                                <div class="body">
                                    <form method="post" class="form-auth-medium" class="form-group">
                                        {% csrf_token %}
                                        {{form.as_p}}
                                        <!-- <div class="form-group">
                                    <label class="control-label sr-only">old password</label>
                                    <input type="email" class="form-control" placeholder="type old password">
                                </div>
                                <div class="form-group">
                                    <label class="control-label sr-only">new password</label>
                                    <input type="email" class="form-control" placeholder="type new password">
                                </div>
                                <div class="form-group">
                                    <label class="control-label sr-only">Password</label>
                                    <input type="password" class="form-control" placeholder="Password">
                                </div> -->
                                        <button type="submit" class="btn btn-primary btn-lg btn-block">update</button>
                                    </form>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
</div>
</div>

{% endblock %}

templates/dealer/delete_bill.html
{% extends 'dealer/partials/base.html' %}
{% load static %}
{% block content %}

<style>
    th, td{
        text-align: center;
    }
</style>

<div id="main-content">
    <div class="container-fluid">
        <div class="block-header">
            <div class="row">
                <div class="col-lg-5 col-md-8 col-sm-12">                        
                    <ul class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{% url 'dealer:index' %}"><i class="icon-home"></i></a></li>                            
                        <li class="breadcrumb-item">Delete Bill</li>
                    </ul>
                </div>            
             
            </div>
        </div>
        
        <div class="row clearfix">
            <div class="col-lg-12">
<div class="card">
    <div class="header">
        <h6>Bill ID : {{bill.id}}</h6>
        <h6>Date : {{bill.date}}</h6>
        <h6>User : {% if bill.customer == '' %}
            {{ bill.user }}
            {% else %}
            {{ bill.customer }}
            {% endif %}</h6>
        <a onclick="deleteBill()" href="{% url 'dealer:deleting_bill' bill.id %}" class="btn btn-danger"><i class="fa fa-trash-o"></i></a>
    </div>
    <div class="body">
        <div class="table-responsive">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>Game</th>                                    
                        <th>Number</th>                                   
                        <th>Count</th>
                        <th>Delete</th>
                    </tr>
                </thead>
                    <tbody>
                        {% regroup bill.dealer_games.all|dictsort:"id" by id as games_by_id %}
                        {% for group in games_by_id %}
                            {% for game in group.list %}
                                <tr>
                                    <td>{{ game.LSK }}</td>
                                    <td>{{ game.number }}</td> 
                                    <td>{{ game.count }}</td>                                  
                                    <td>
                                        <a href="{% url 'dealer:deleting_row' game.id bill.id %}" class="btn btn-danger"><i class="fa fa-trash-o"></i></a>
                                    </td>
                                </tr>
                            {% endfor %}
                        {% endfor %}  
                </tbody>
            </table>
        </div>
    </div>
</div>
</div>
</div>
</div>
</div>

<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

<script>
    function deleteBill(){
        console.log("working")
        Swal.fire({
           icon: 'success',
           title: 'Deleted!',
           text: 'Bill deleted successfully.',
           timer: 3000,
           showConfirmButton: false
       });
    }
</script>


{% endblock %}

templates/dealer/edit_bill.html
{% extends 'dealer/partials/base.html' %}
{% load static %}
{% block content %}
<style>
    .table-cell {
        border: 1px solid #d2d2d2; /* Add a 1px black border to each cell */
        text-align: center;
}

    .nav {
        position: fixed;
        bottom: 0;
        width: 100%;
        height: 55px;
        box-shadow: 0 0 10px rgba(0,0,0,0.2);
        background-color: #ffffff;
        overflow-x: auto;
        justify-content: space-evenly;
        display: flex;
        flex-direction: column;
    }

    th, td{
        text-align: center;
    }
</style>
<div id="main-content">
    <div class="container-fluid">
        <div class="block-header">
            <div class="row">
                <div class="col-lg-5 col-md-8 col-sm-12">                        
                    
                    <ul class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{% url 'dealer:index' %}"><i class="icon-home"></i></a></li>                            
                        <li class="breadcrumb-item">Edit Bill</li>
                    </ul>
                </div>            
             
            </div>
        </div>

        <div class="row clearfix">
            <div class="col-lg-12 col-md-12 col-sm-12">
                <div class="card">
                    <div class="header">
                        <h2>Edit Bill</h2>
                    </div>
                    <div class="body">
                        <div class="col-lg-12">
                            <div class="card">
                                
                                <div class="body">
                                    <div class="row clearfix">
                                        
                                        
 
                                     <div class="col-lg-2 col-md-6 col-sm-12">
                                        <div class="form-group">
                                            <label for="tax-id"  name="dealer"   style="font-size: larger;"  class="control-label"> Dealer  : {{request.user}}</label>
                                        </div>
                                    </div>
                                                
                                      
                                    </div>
                                   
                                 </div>
                                
                                <div class="body">
                                    <div class="table-responsive">
                                        <table class="table m-b-0">
                                            <thead>
                                                <tr>
                                                    <th>Date</th>
                                                    <th>User</th>
                                                    <th>Bill</th>
                                                    <th>Count </th>
                                                    <th>S Amount </th>
                                                    <th>C Amount </th>
                                                    <th>#</th>
                                                     
                                                    
                                                </tr>
                                            </thead>
                                            <tbody id="bill-table">
                                                {% for bill in bills %}
                                                <tr data-dealer="{{ bill.agent.user }}">
                                                    <td class="table-cell">{{ bill.created_at|date:"N j, Y" }}<br>{{ bill.created_at|time:"H:i" }}</td>
                                                    {% if bill.customer == '' %}
                                                    <td>{{ bill.user }}</td>
                                                    {% else %}
                                                    <td>{{ bill.customer }}</td>
                                                    {% endif %}
                                                    <td class="table-cell">{{bill.id}}</td>
                                                    <td class="table-cell">{{bill.total_count}}</td>
                                                    <td class="table-cell">{{bill.total_d_amount}}</td>
                                                    <td class="table-cell">{{bill.total_c_amount}}</td>
                                                    <td class="table-cell"><a href="{% url 'dealer:delete_bill' bill.id %}">Edit</a></td>
                                                </tr>
                                                {% endfor %}
                                            </tbody>
                                        </table>
                                    </div>
                                   
                                </div>
                           
                                
                            </div>
                           
                        </div>
                    </div>
                    </div>
                </div>
            </div>
        </div>
        
    </div>
</div>
<nav class="nav">
    <table>
        <thead>
            <tr>
                 <th class="th">Total Count</th>
                 <th class="th">A.Amount</th>
                 <th class="th">C.Amount</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td class="td">{{totals.total_count}}</td>
                <td class="td">{{totals.total_d_amount|floatformat:2 }}</td>
                <td class="td">{{totals.total_c_amount|floatformat:2 }}</td>
            </tr>
        </tbody>
    </table>
</nav>
{% endblock %} 