agent/urls.py
from django.urls import path
from . import views

app_name = 'agent'

urlpatterns = [
    path("index",views.index,name='index'),
    path('add-dealer',views.add_dealer,name="add_dealer"), 
    path('view-dealer',views.view_dealer,name="view_dealer"),
    path('ban-dealer/<int:id>',views.ban_dealer,name="ban_dealer"),
    path('remove-ban/<int:id>',views.remove_ban,name="remove_ban"),
    path('remove-ban/<int:id>',views.remove_ban,name="remove_ban"),
    path('delete-dealer/<int:id>',views.delete_dealer,name="delete_dealer"),
    path('edit-dealer/<int:id>',views.edit_dealer,name="edit_dealer"),
    path('Results',views.results,name="results"),

    path('booking',views.booking,name="booking"), 
    path('sales-report',views.sales_report,name="sales_report"), 
    path('daily-report',views.daily_report,name="daily_report"), 
    path('winning-report',views.winning_report,name="winning_report"),
    path('count-salesreport',views.count_salereport,name="count_salereport"),
    path('winning_countreport',views.winning_countreport,name="winning_countreport"),
    path('collection-report',views.payment_report,name="collection_report"),
    path('add-collection',views.add_collection,name="add_collection"),
    path('balance-report',views.balance_report,name="balance_report"),
    path('edit-bill-times',views.edit_bill_times,name="edit_bill_times"),
    path('edit-bill/<int:id>',views.edit_bill,name="edit_bill"),

    path('play-game/<int:id>',views.play_game,name="play_game"),

    path('package',views.package,name="package"),
    path('new-package',views.new_package,name="new_package"),
    path('edit-package/<int:id>',views.edit_package,name="edit_package"),
    path('delete-package/<int:id>',views.delete_package,name="delete_package"),
    path('check-limit/',views.check_limit, name='check_limit'),
    path('save-data/',views.save_data,name="save_data"),

    path('delete-test-row/<str:id>/',views.agent_game_test_delete,name="agent_game_test_delete"),
    path('update-test-row/<str:id>',views.agent_game_test_update,name="agent_game_test_update"),

    path('delete-bill/<int:id>',views.delete_bill,name="delete_bill"),
    path('deleting-bill/<int:id>',views.deleting_bill,name="deleting_bill"),
    path('deleting-row/<int:id>/<int:bill_id>',views.delete_row,name="deleting_row"),


    path('set-limit',views.set_limit,name="set_limit"),
    path('view-limit',views.view_limits,name="view_limits"),
    path('edit-limit/<int:id>',views.edit_limit,name="edit_limit"),
    path('change-password',views.change_password,name="change_password"),
    path('total-balance',views.total_balance,name="total_balance"),



]

guessmaster/urls.py
from django.contrib import admin
from django.urls import URLPattern, path, include
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path('adminapp/',include('adminapp.urls')),
    path('',include('website.urls')),
    path('agent/',include('agent.urls')),
    path('dealer/',include('dealer.urls')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/urls.py
from . import views
from django.urls import path

app_name = 'website'

urlpatterns = [
    path('login',views.login,name="login"),
    path('logout',views.logout_view,name="logout"),
    path('',views.lock,name="lock")
]

agent/views.py
from audioop import reverse
import json
from urllib import response
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render,redirect,get_object_or_404
from django.contrib.auth.decorators import login_required
import pytz
from website.forms import LoginForm
from website.forms import DealerRegistration,UserUpdateForm
from website.models import User,Dealer,Agent
from adminapp.models import PlayTime, AgentPackage,Result,Winning,Limit,BlockedNumber,GameLimit,CollectionReport
from .models import DealerPackage, AgentGameTest, AgentGame, Bill, DealerCollectionReport, DealerLimit
from dealer.models import DealerGame, DealerGameTest
from django.contrib import messages
from django.views.decorators.csrf import csrf_exempt
from website.decorators import dealer_required, agent_required
from django.utils import timezone
from pytz import timezone as pytz_timezone
from collections import OrderedDict
from django.db.models import Sum
from django.db.models import Q
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.forms import PasswordChangeForm,AdminPasswordChangeForm
from django.db.models import F
from django.views.decorators.http import require_http_methods
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph
from django.http import HttpResponse
from reportlab.lib.styles import ParagraphStyle
from reportlab.platypus import Paragraph, Spacer
from datetime import datetime, timedelta

# Create your views here.
@login_required
@agent_required
def index(request):
    ist = pytz_timezone('Asia/Kolkata')
    current_time = timezone.now().astimezone(ist).time()
    print(current_time)
    agent_obj = Agent.objects.get(user=request.user)
    if PlayTime.objects.filter(limit__agent=agent_obj).all():
        play_times = PlayTime.objects.filter(limit__agent=agent_obj).all().order_by('id')
    else:
        play_times = PlayTime.objects.filter().all().order_by('id')
    play_time_availabilities = []
    for time in play_times:
        if time.start_time <= current_time <= time.end_time:
            play_time_availabilities.append(True)
        else:
            play_time_availabilities.append(False)
    zipped_play_times = zip(play_times, play_time_availabilities)
    context = {
        'play_times': play_times,
        'zipped_play_times': zipped_play_times,
    }
    return render(request,"agent/index.html",context)

@login_required
@agent_required
@csrf_exempt
def add_dealer(request):
    login_form = LoginForm()
    dealer_form = DealerRegistration()
    agent_obj = Agent.objects.get(user=request.user)
    if request.method == "POST":
        dealer_form = DealerRegistration(request.POST)
        login_form = LoginForm(request.POST)
        print(dealer_form)
        print(login_form)
        if login_form.is_valid() and dealer_form.is_valid():
            print("loginform is working")
            user = login_form.save(commit=False)
            user.is_dealer = True
            user.save()
            dealer = dealer_form.save(commit=False)
            dealer.user = user
            dealer.agent = agent_obj  # Associate the agent_obj with the dealer
            dealer.save()
            messages.info(request, "Dealer Created Successfully")
            return redirect("agent:new_package")
    return render(request,'agent/add_dealer.html',{"login_form": login_form, "dealer_form": dealer_form})

@login_required
@agent_required
def view_dealer(request):
    agent = Agent.objects.get(user=request.user)
    print(agent)
    dealers = Dealer.objects.filter(agent=agent).all()
    packages = DealerPackage.objects.filter().all()
    context = {
        'dealers' : dealers,
        'packages' : packages
    }
    return render(request,'agent/view_dealer.html',context)

@login_required
@agent_required
def edit_dealer(request,id):
    dealer = get_object_or_404(Dealer, id=id)
    user = dealer.user
    if request.method == 'POST':
        form = AdminPasswordChangeForm(user=user, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect("agent:view_dealer")
    else:
        form = AdminPasswordChangeForm(user=user)

    return render(request, 'agent/edit_dealer.html', {'form': form})


@login_required
@agent_required
def delete_dealer(request,id):
    dealer = get_object_or_404(Dealer, id=id)
    dealer_user = dealer.user
    dealer_user.delete()
    return redirect('agent:view_dealer')

@login_required
@agent_required
def ban_dealer(request,id):
    dealer = get_object_or_404(Dealer, id=id)
    user = dealer.user
    user.is_active = False
    user.save()
    return redirect('agent:view_dealer')

@login_required
@agent_required
def remove_ban(request,id):
    dealer = get_object_or_404(Dealer,id=id)
    user = dealer.user
    user.is_active = True
    user.save()
    return redirect('agent:view_dealer')

@login_required
@agent_required
def booking(request):
    return render(request,'agent/booking.html')

@login_required
@agent_required
def results(request):
    ist = pytz.timezone('Asia/Kolkata')
    current_date = timezone.now().astimezone(ist).date()
    times = PlayTime.objects.filter().all().order_by('id')
    results = Result.objects.filter(date=current_date).last()
    if request.method == 'POST':
        date = request.POST.get('date')
        time = request.POST.get('time')
        try:
            results = Result.objects.get(date=date,time=time)
        except:
            results = []
        context = {
            'times' : times,
            'results' : results,
            'selected_date' : date,
            'selected_time' : time,
        }
        return render(request,'agent/results.html',context)
    context = {
        'times' : times,
        'results' : results
    }
    return render(request,'agent/results.html',context)

@login_required
@agent_required
def sales_report(request):
    print("Sales report function")
    agent_obj = Agent.objects.get(user=request.user)
    print(agent_obj)
    dealers = Dealer.objects.filter(agent=agent_obj).all()
    times = PlayTime.objects.filter().all().order_by('id')
    ist = pytz.timezone('Asia/Kolkata')
    current_date = timezone.now().astimezone(ist).date()
    day_of_week = current_date.strftime('%A')
    print(day_of_week)
    print(current_date)
    items_per_page = 15
    if request.method == 'POST':
        select_dealer = request.POST.get('select-dealer')
        print(select_dealer,"selected_dealer")
        select_time = request.POST.get('select-time')
        from_date = request.POST.get('from-date')
        to_date = request.POST.get('to-date')
        lsk = request.POST.get('select-lsk')
        print(from_date,"fromdate")
        print(to_date,"todate")
        try:
            selected_game_time = PlayTime.objects.get(id=select_time)
        except:
            selected_game_time = 'all times'
        lsk_value = []
        agent_bills = []
        dealer_bills = []
        agent_games = []
        dealer_games = []
        totals = []
        if lsk == 'a_b_c':
            lsk_value = ['A','B','C']
        elif lsk == 'ab_bc_ac':
            lsk_value = ['AB','BC','AC']
        elif lsk == 'super':
            lsk_value = ['Super']
        elif lsk == 'box':
            lsk_value = ['Box']
        else:
            lsk_value == ['all']
        print(lsk_value,"##################")
        if select_dealer != 'all':
            if str(select_dealer) != str(agent_obj.user) and not str(select_dealer).isdigit():
                if select_time != 'all':
                    selected_time = selected_game_time.game_time.strftime("%I:%M %p")
                    #time and agent is selected
                    if lsk != 'all':
                        #time, agent and lsk is selected
                        agent_games = AgentGame.objects.filter(date__range=[from_date, to_date],agent=agent_obj,time=select_time,LSK__in=lsk_value,customer=select_dealer).order_by('id')
                        print(agent_games)
                        agent_bills = Bill.objects.filter(date__range=[from_date, to_date],user=agent_obj.user.id,time_id=select_time,agent_games__in=agent_games,customer=select_dealer).distinct().order_by('-id')
                        print(agent_bills)
                        totals = AgentGame.objects.filter(date__range=[from_date, to_date],time=select_time,agent=agent_obj,LSK__in=lsk_value,customer=select_dealer).aggregate(total_count=Sum('count'),total_c_amount=Sum('c_amount'),total_d_amount=Sum('d_amount'))
                        customers_list = []
                        customers = Bill.objects.filter(date__range=[from_date, to_date],user=agent_obj.user.id,time_id=select_time,agent_games__in=agent_games).exclude(customer='').order_by('-id')
                        for cust in customers:
                            if cust.customer not in customers_list:
                                customers_list.append(cust.customer)
                        combined_queryset = agent_bills
                        paginator = Paginator(combined_queryset, 100)
                        page = request.POST.get('page', 1)
                        try:
                            combined_bills = paginator.page(page)
                        except PageNotAnInteger:
                            combined_bills = paginator.page(1)
                        except EmptyPage:
                            combined_bills = paginator.page(paginator.num_pages)
                        for bill in agent_bills:
                            for game in bill.agent_games.filter(LSK__in=lsk_value):
                                print("Game Count of",bill.id," is" , game.count)

templates/agent/partials/base.html
{% load static %}
<!doctype html>
<html lang="en">


<!-- Mirrored from www.wrraptheme.com/templates/lucid/html/light/index7.html by HTTrack Website Copier/3.x [XR&CO'2014], Sat, 09 Sep 2023 12:05:13 GMT -->
<head>
<title>AGENT</title>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge, chrome=1">
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
<meta name="description" content="Lucid Bootstrap 4.1.1 Admin Template">
<meta name="author" content="WrapTheme, design by: ThemeMakker.com">

<link rel="icon" href="{% static 'outgoing-call.png' %}" type="image/x-icon">
<!-- VENDOR CSS -->
<link rel="stylesheet" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'vendor/font-awesome/css/font-awesome.min.css' %}">
<link rel="stylesheet" href="{% static 'vendor/chartist/css/chartist.min.css' %}">
<link rel="stylesheet" href="{% static 'vendor/chartist-plugin-tooltip/chartist-plugin-tooltip.css' %}">
<link rel="stylesheet" href="{% static 'vendor/jvectormap/jquery-jvectormap-2.0.3.min.css' %}"/>
<link rel="stylesheet" href="{% static 'vendor/jquery-datatable/dataTables.bootstrap4.min.css' %}">

<!-- MAIN CSS -->
<link rel="stylesheet" href="{% static 'css/main.css' %}">
<link rel="stylesheet" href="{% static 'css/color_skins.css' %}">
</head>
<body class="theme-cyan" style="background-color:#e7daff;">

        <!-- Your webpage content goes here -->
      
        <script>
          // Function to handle the touchstart and touchmove events
          function handleTouch(event) {
            // Check if the touch event started from the top of the page
            if (event.targetTouches[0].clientY <= 10) {
              // Prevent the default behavior (in this case, page refresh)
              event.preventDefault();
            }
          }
      
          // Add event listeners for touchstart and touchmove
          document.addEventListener('touchstart', handleTouch, { passive: false });
          document.addEventListener('touchmove', handleTouch, { passive: false });
        </script>
    <!-- Overlay For Sidebars -->

<div id="wrapper">

    {% include 'agent/partials/header.html' %}
    {% include 'agent/partials/sidebar.html' %}

    {% block content %}

    {% endblock %}

</div>

<!-- Javascript -->
<script src="https://rawgit.com/eKoopmans/html2pdf/master/dist/html2pdf.bundle.js"></script>

<script src="{% static 'bundles/libscripts.bundle.js' %}"></script>    
<script src="{% static 'bundles/vendorscripts.bundle.js' %}"></script>

<script src="{% static 'bundles/jvectormap.bundle.js' %}"></script> <!-- JVectorMap Plugin Js -->
<script src="{% static 'bundles/chartist.bundle.js' %}"></script>
<script src="{% static 'bundles/datatablescripts.bundle.js' %}"></script>

<script src="{% static 'bundles/mainscripts.bundle.js' %}"></script>
<script src="{% static 'js/pages/tables/jquery-datatable.js' %}"></script>
<script src="{% static 'js/index7.js' %}"></script>

</body>

</html>

templates/agent/partials/header.html
{% load static %}
  
    
        <nav class="navbar navbar-fixed-top">
            <div class="container-fluid">
                <div class="navbar-btn">
                    <button type="button" class="btn-toggle-offcanvas"><i class="lnr lnr-menu fa fa-bars"></i></button>
                </div>
    
                <div class="navbar-brand">
                    <a href="{% url 'agent:index' %}"><img src="" class="img-responsive logo"></a>                
                </div>
                
                <div class="navbar-right">
                    
                </div>
            </div>
        </nav>
    
        

templates/agent/partials/sidebar.html
{% load static %}
<div id="left-sidebar" class="sidebar">
    <div class="sidebar-scroll">
        <div class="user-account">
            <div class="dropdown">
                <span>Welcome,</span>
                <a href="javascript:void(0);" class="dropdown-toggle user-name" data-toggle="dropdown"><strong>{{request.user}} (Agent)</strong></a>
                <ul class="dropdown-menu dropdown-menu-right account">
                    
                    <li><a href="{% url 'website:logout' %}"><i class="icon-power"></i>Logout</a></li>
                </ul>
            </div>
            <hr>
          
        </div>
        <!-- Nav tabs -->
      
            
        <!-- Tab panes -->
        <div class="tab-content p-l-0 p-r-0">
            <div class="tab-pane active" id="menu">
                <nav id="left-sidebar-nav" class="sidebar-nav">
                    <ul id="main-menu" class="metismenu">                            
                        <li class="active">
                           
                                <a href="{% url 'agent:index' %}" ><i class="icon-home"></i> <span>Dashboard</span></a>

                            </li>
                        <li>
                            <a href="#App" class="has-arrow"><i class=" icon-users"></i> <span>Dealer</span></a>
                            <ul>
                                <li><a href="{% url 'agent:add_dealer' %}">Add Dealer</a></li> 
                                <li><a href="{% url 'agent:view_dealer' %}">View Dealer</a></li>                                    
                                   
                                
                            </ul>
                        </li>
                        <li>
                            <a href="{% url 'agent:sales_report' %}" ><i class="icon-notebook"></i> <span>Sales Report</span></a>
                           
                        </li>
                        <li>
                            <a href="{% url 'agent:daily_report' %}" ><i class="icon-book-open"></i> <span>Daily Report</span></a>
                           
                        </li>
                        <li>
                            <a href="{% url 'agent:results' %}" ><i class=" icon-trophy"></i> <span>Results</span></a>
                           
                        </li>
                        <li>
                            <a href="#Limit" class="has-arrow"><i class="icon-bar-chart"></i> <span>Daily Limit</span></a>
                            <ul>
                                <li><a href="{% url 'agent:set_limit' %}">Set Limit</a></li>                                    
                                <li><a href="{% url 'agent:view_limits' %}">Edit Limit</a></li>
                                
                            </ul>
                        </li>
                        <li>
                            <a href="#Dashboard" class="has-arrow"><i class="icon-present"></i> <span>Package</span></a>
                            <ul>
                                <li><a href="{% url 'agent:package' %}">Package</a></li>                                    
                                <li><a href="{% url 'agent:new_package' %}">New Package</a></li>
                                
                            </ul>
                        </li>
                      
                      
                        <li>
                            <a href="#uiElements" class="has-arrow"><i class="icon-book-open "></i> <span>Reports</span></a>
                            <ul>
                                <li>
                                    <a href=" {% url 'agent:winning_report' %}"><span>Winning Report</span></a>
                                 
                                </li>
                                
                                <li>
                                    <a href=" {% url 'agent:count_salereport' %}"><span>Count Sales Report</span></a>
                                 
                                </li>
                                <li>
                                    <a href=" {% url 'agent:winning_countreport' %}"><span>Winnning Count Report</span></a>
                                 
                                </li>
                                <li>
                                    <a href=" {% url 'agent:balance_report' %}"><span>Balance Report</span></a>
                                 
                                </li>
                               
                               
                           
                            </ul>
                        </li>
                        <li>
                            <a href="{% url 'agent:edit_bill_times' %}" ><i class="icon-note"></i> <span>Edit Bill</span></a>
                           
                        </li>
                        <li>
                            <a href="#" class="has-arrow"><i class="icon-grid"></i> <span>Collection</span></a>
                            <ul>
                               
                                
                                <li>
                                    <a href=" {% url 'agent:collection_report' %}"><i class="icon-book-open "></i> <span>Collection Report</span></a>
                                 
                                </li>
                                <li>
                                    <a href=" {% url 'agent:add_collection' %}"><i class="icon-book-open "></i> <span> Add Collection</span></a>
                                 
                                </li>
                                
                               
                           
                            </ul>
                        </li>
                        <li>
                            <a href=" {% url 'agent:total_balance' %}" ><i class="icon-note"></i> <span>Total Balance</span></a>
                         
                        </li>
                        <li>
                            <a href="{% url 'agent:change_password' %}" class="has-arrow"><i class="icon-wrench"></i> <span>Change Password</span></a>
                        </li>
                       
                        
                        
                       
                     
                    </ul>
                </nav>
            </div>
              
        </div>          
    </div>
</div>