agent/urls.py
from django.urls import path
from . import views

app_name = 'agent'

urlpatterns = [
    path("index",views.index,name='index'),
    path('add-dealer',views.add_dealer,name="add_dealer"), 
    path('view-dealer',views.view_dealer,name="view_dealer"),
    path('ban-dealer/<int:id>',views.ban_dealer,name="ban_dealer"),
    path('remove-ban/<int:id>',views.remove_ban,name="remove_ban"),
    path('remove-ban/<int:id>',views.remove_ban,name="remove_ban"),
    path('delete-dealer/<int:id>',views.delete_dealer,name="delete_dealer"),
    path('edit-dealer/<int:id>',views.edit_dealer,name="edit_dealer"),
    path('Results',views.results,name="results"),

    path('booking',views.booking,name="booking"), 
    path('sales-report',views.sales_report,name="sales_report"), 
    path('daily-report',views.daily_report,name="daily_report"), 
    path('winning-report',views.winning_report,name="winning_report"),
    path('count-salesreport',views.count_salereport,name="count_salereport"),
    path('winning_countreport',views.winning_countreport,name="winning_countreport"),
    path('collection-report',views.payment_report,name="collection_report"),
    path('add-collection',views.add_collection,name="add_collection"),
    path('balance-report',views.balance_report,name="balance_report"),
    path('edit-bill-times',views.edit_bill_times,name="edit_bill_times"),
    path('edit-bill/<int:id>',views.edit_bill,name="edit_bill"),

    path('play-game/<int:id>',views.play_game,name="play_game"),

    path('package',views.package,name="package"),
    path('new-package',views.new_package,name="new_package"),
    path('edit-package/<int:id>',views.edit_package,name="edit_package"),
    path('delete-package/<int:id>',views.delete_package,name="delete_package"),
    path('check-limit/',views.check_limit, name='check_limit'),
    path('save-data/',views.save_data,name="save_data"),

    path('delete-test-row/<str:id>/',views.agent_game_test_delete,name="agent_game_test_delete"),
    path('update-test-row/<str:id>',views.agent_game_test_update,name="agent_game_test_update"),

    path('delete-bill/<int:id>',views.delete_bill,name="delete_bill"),
    path('deleting-bill/<int:id>',views.deleting_bill,name="deleting_bill"),
    path('deleting-row/<int:id>/<int:bill_id>',views.delete_row,name="deleting_row"),


    path('set-limit',views.set_limit,name="set_limit"),
    path('view-limit',views.view_limits,name="view_limits"),
    path('edit-limit/<int:id>',views.edit_limit,name="edit_limit"),
    path('change-password',views.change_password,name="change_password"),
    path('total-balance',views.total_balance,name="total_balance"),



]

dealer/urls.py
from django.urls import path
from . import views


app_name = 'dealer'

urlpatterns = [

    path("index",views.index,name='index'),
    path('booking',views.booking,name="booking"), 
    path('result',views.result,name="result"), 
    path('edit-bill',views.edit_bill,name="edit_bill"),
    path('sales-report',views.sales_report,name="sales_report"),
    path('daily-report',views.daily_report,name="daily_report"), 
    path('winning-report',views.winning_report,name="winning_report"),
    path('count-salesreport',views.count_salereport,name="count_salereport"),
    path('winning_countreport',views.winning_countreport,name="winning_countreport"),
    path('balance-report',views.balance_report,name="balance_report"),
    path('play-game/<int:id>',views.play_game,name="play_game"),
    path('check-limit/',views.check_limit,name="check_limit"),
    path('save-data/',views.save_data,name="save_data"),
    path('edit-bill-times',views.edit_bill_times,name="edit_bill_times"),
    path('edit-bill/<int:id>',views.edit_bill,name="edit_bill"),
    path('delete-bill/<int:id>',views.delete_bill,name="delete_bill"),
    path('deleting-bill/<int:id>',views.deleting_bill,name="deleting_bill"),
    path('change-password',views.change_password,name="change_password"),
    path('deleting-row/<int:id>/<int:bill_id>',views.delete_row,name="deleting_row"),

    path('delete-test-row/<str:id>/',views.dealer_game_test_delete,name="dealer_game_test_delete"),
    path('update-test-row/<str:id>',views.dealer_game_test_update,name="dealer_game_test_update"),

]

guessmaster/urls.py
from django.contrib import admin
from django.urls import URLPattern, path, include
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path('adminapp/',include('adminapp.urls')),
    path('',include('website.urls')),
    path('agent/',include('agent.urls')),
    path('dealer/',include('dealer.urls')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/urls.py
from . import views
from django.urls import path

app_name = 'website'

urlpatterns = [
    path('login',views.login,name="login"),
    path('logout',views.logout_view,name="logout"),
    path('',views.lock,name="lock")
]

dealer/models.py
from django.db import models
from agent.models import Agent,Dealer
from adminapp.models import PlayTime

# Create your models here.

class DealerGameTest(models.Model):
    agent = models.ForeignKey(Agent,on_delete=models.CASCADE,null=True, related_name='agent_dealergametests')
    created_by = models.ForeignKey(Agent,on_delete=models.CASCADE,null=True)
    customer = models.CharField(max_length=100,null=True)
    dealer = models.ForeignKey(Dealer,on_delete=models.CASCADE,null=True)
    time = models.ForeignKey(PlayTime,on_delete=models.CASCADE,null=True)
    date = models.DateField(auto_now_add=True)
    LSK = models.CharField(max_length=100)
    number = models.CharField(max_length=100)
    count = models.IntegerField()
    d_amount = models.FloatField()
    c_amount = models.FloatField()
    d_amount_admin = models.FloatField()
    c_amount_admin = models.FloatField()

    def __str__(self):
        return str(self.dealer)
    
class DealerGame(models.Model):
    agent = models.ForeignKey(Agent,on_delete=models.CASCADE,null=True)
    dealer = models.ForeignKey(Dealer,on_delete=models.CASCADE,null=True)
    customer = models.CharField(max_length=100,null=True)
    time = models.ForeignKey(PlayTime,on_delete=models.CASCADE,null=True)
    date = models.DateField(auto_now_add=True)
    LSK = models.CharField(max_length=100)
    number = models.CharField(max_length=100)
    count = models.IntegerField()
    d_amount = models.FloatField()
    c_amount = models.FloatField()
    d_amount_admin = models.FloatField()
    c_amount_admin = models.FloatField()
    combined = models.BooleanField()

    def __str__(self):
        return str(self.dealer)

dealer/views.py
import json
from django.http import JsonResponse
from django.shortcuts import render,get_object_or_404,redirect
import pytz
from website.decorators import dealer_required, agent_required
from django.contrib.auth.decorators import login_required
from adminapp.models import PlayTime, Result, Winning, BlockedNumber, GameLimit, AgentPackage, Limit
from agent.models import DealerPackage,Bill,DealerCollectionReport,AgentGame,AgentGameTest,DealerLimit
from website.models import Dealer
from dealer.models import DealerGame,DealerGameTest
from django.utils import timezone
from django.views.decorators.csrf import csrf_exempt
from pytz import timezone as pytz_timezone
from collections import OrderedDict
from django.contrib import messages
from django.db.models import Sum
from django.db.models import Q
from django.db.models import F
from django.contrib.auth.forms import PasswordChangeForm
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph
from django.http import HttpResponse
from reportlab.lib.styles import ParagraphStyle
from reportlab.platypus import Paragraph, Spacer



# Create your views here.
@dealer_required
@login_required
def index(request):
    ist = pytz_timezone('Asia/Kolkata')
    dealer_obj = Dealer.objects.get(user=request.user)
    agent = dealer_obj.agent
    print(agent)
    current_time = timezone.now().astimezone(ist).time()
    print(current_time)
    if PlayTime.objects.filter(dealerlimit__dealer=dealer_obj).all():
        play_times = PlayTime.objects.filter(dealerlimit__dealer=dealer_obj).all().order_by('id')
    else:
        play_times = PlayTime.objects.filter().all().order_by('id')
    play_time_availabilities = []
    for time in play_times:
        if time.start_time <= current_time <= time.end_time:
            play_time_availabilities.append(True)
        else:
            play_time_availabilities.append(False)
    zipped_play_times = zip(play_times, play_time_availabilities)
    context = {
        'play_times': play_times,
        'zipped_play_times': zipped_play_times,
    }
    return render(request,"dealer/index.html",context)

@dealer_required
@login_required
def booking(request):
    return render(request,'dealer/booking.html')

@dealer_required
@login_required
def result(request):
    ist = pytz.timezone('Asia/Kolkata')
    current_date = timezone.now().astimezone(ist).date()
    times = PlayTime.objects.filter().all().order_by('id')
    results = Result.objects.filter(date=current_date).last()
    if request.method == 'POST':
        date = request.POST.get('date')
        time = request.POST.get('time')
        try:
            results = Result.objects.get(date=date,time=time)
        except:
            results = []
        context = {
            'times' : times,
            'results' : results,
            'selected_date' : date,
            'selected_time' : time,
        }
        return render(request,'dealer/results.html',context)
    context = {
        'times' : times,
        'results' : results
    }
    return render(request,'dealer/results.html',context)

@dealer_required
@login_required
def edit_bill_times(request):
    ist = pytz_timezone('Asia/Kolkata')
    current_time = timezone.now().astimezone(ist).time()
    matching_play_times = PlayTime.objects.filter(Q(start_time__lte=current_time) & Q(end_time__gte=current_time)).order_by('id')
    context = {
        'times' : matching_play_times
    }
    return render(request,'dealer/edit_bill_times.html',context)

@dealer_required
@login_required
def edit_bill(request,id):
    dealer_obj = Dealer.objects.get(user=request.user)
    print(dealer_obj.user,"dealer id")
    ist = pytz_timezone('Asia/Kolkata')
    current_date = timezone.now().astimezone(ist).date()
    current_time = timezone.now().astimezone(ist).time()
    print(current_time)
    try:
        time = PlayTime.objects.get(id=id)
    except:
        matching_play_times = []
    try:
        totals = Bill.objects.filter(user=dealer_obj.user,time_id=time,date=current_date).aggregate(total_count=Sum('total_count'),total_c_amount=Sum('total_c_amount'),total_d_amount=Sum('total_d_amount'))
        bills = Bill.objects.filter(user=dealer_obj.user,time_id=time,date=current_date).all().order_by('-id')
        context = {
            'bills' : bills,
            'totals': totals,
        } 
    except:
        totals = []
        bills = []
        context = {
            'bills' : bills,
            'totals': totals,
        }
    return render(request,'dealer/edit_bill.html',context)

@dealer_required
@login_required
def delete_bill(request,id):
    print(id)
    bill = Bill.objects.get(id=id)
    user_obj = bill.user
    print(user_obj)
    time_id = bill.time_id
    print(time_id,"time")
    date = bill.date
    print(date,"date")
    games = DealerGame.objects.filter(dealer__user=user_obj.id,time=time_id,date=date).order_by('id')
    context = {
            'bill' : bill,
            'games' : games
        }
    return render(request,'dealer/delete_bill.html',context)  

@dealer_required
@login_required
def deleting_bill(request,id):
    bill = get_object_or_404(Bill,id=id)
    print(bill,"deleting bill")
    bill.delete()
    return redirect('dealer:index')

@dealer_required
@login_required
def delete_row(request,id,bill_id):
    print(id,"this row")
    bill = get_object_or_404(Bill, id=bill_id)
    row_delete = get_object_or_404(DealerGame,id=id)
    row_delete.delete()
    bill.update_totals_dealer()
    return redirect('dealer:delete_bill',id=bill_id)

def dealer_game_test_delete(request,id):
    print(id,"row id")
    row = get_object_or_404(DealerGameTest,id=id)
    row.delete()
    return JsonResponse({'status':'success'})

def dealer_game_test_update(request,id):
    dealer_obj = Dealer.objects.get(user=request.user)
    agent_obj = dealer_obj.agent
    dealer_package = DealerPackage.objects.get(dealer=dealer_obj)
    amounts = {
        "A": dealer_package.single_rate,
        "B": dealer_package.single_rate,
        "C": dealer_package.single_rate,
        "AB": dealer_package.double_rate,
        "BC": dealer_package.double_rate,
        "AC": dealer_package.double_rate,
        "Super": dealer_package.super_rate,
        "Box": dealer_package.box_rate,
    }
    dcs = {
        "A": dealer_package.single_dc,
        "B": dealer_package.single_dc,
        "C": dealer_package.single_dc,
        "AB": dealer_package.double_dc,
        "BC": dealer_package.double_dc,
        "AC": dealer_package.double_dc,
        "Super": dealer_package.super_dc,
        "Box": dealer_package.box_dc,
    }
    print(amounts)
    print(dcs)
    agent_package = AgentPackage.objects.get(agent=agent_obj)
    amounts_agent = {
        "A": agent_package.single_rate,
        "B": agent_package.single_rate,
        "C": agent_package.single_rate,
        "AB": agent_package.double_rate,
        "BC": agent_package.double_rate,
        "AC": agent_package.double_rate,
        "Super": agent_package.super_rate,
        "Box": agent_package.box_rate,
    }
    dcs_agent = {
        "A": agent_package.single_dc,
        "B": agent_package.single_dc,
        "C": agent_package.single_dc,
        "AB": agent_package.double_dc,
        "BC": agent_package.double_dc,
        "AC": agent_package.double_dc,
        "Super": agent_package.super_dc,
        "Box": agent_package.box_dc,
    }
    if request.method == 'POST':
        data = json.loads(request.body.decode('utf-8'))
        edited_count = data.get('editedCount')
        print(edited_count)
        test_game = DealerGameTest.objects.get(id=id)
        lsk = test_game.LSK
        updated_d_amount = amounts[lsk] * float(edited_count)
        updated_c_amount = (amounts[lsk] + dcs[lsk]) * float(edited_count)
        updated_d_amount_agent = amounts_agent[lsk] * float(edited_count)
        updated_c_amount_agent = (amounts_agent[lsk] + dcs_agent[lsk]) * float(edited_count)
        DealerGameTest.objects.filter(id=id).update(count=edited_count,d_amount=updated_d_amount,c_amount=updated_c_amount,d_amount_admin=updated_d_amount_agent,c_amount_admin=updated_c_amount_agent)
    return JsonResponse({'status':'success'})

@dealer_required
@login_required
def sales_report(request):
    dealer_bills={}
    totals={}
    select_time={}
    dealer_games={}
    dealer_obj = Dealer.objects.get(user=request.user)
    print(dealer_obj)
    times = PlayTime.objects.filter().all().order_by('id')
    ist = pytz.timezone('Asia/Kolkata')
    current_date = timezone.now().astimezone(ist).date()
    print(current_date)
    items_per_page = 15
    if request.method == 'POST':
        select_time = request.POST.get('select-time')
        lsk = request.POST.get('select-lsk')
        from_date = request.POST.get('from-date')
        to_date = request.POST.get('to-date')
        select_customer = request.POST.get('select-customer')
        try:
            selected_game_time = PlayTime.objects.get(id=select_time)
        except:
            selected_game_time = 'all times'
        lsk_value = []
        dealer_bills = []
        totals = []
        if lsk == 'a_b_c':
            lsk_value = ['A','B','C']
        elif lsk == 'ab_bc_ac':
            lsk_value = ['AB','BC','AC']
        elif lsk == 'super':
            lsk_value = ['Super']
        elif lsk == 'box':
            lsk_value = ['Box']
        else:
            lsk_value == ['all']
        if select_customer == 'all':
            if select_time != 'all':
                selected_time = selected_game_time.game_time.strftime("%I:%M %p")
                if lsk != 'all':

templates/dealer/partials/base.html
{% load static %}
<!doctype html>
<html lang="en">


<!-- Mirrored from www.wrraptheme.com/templates/lucid/html/light/index7.html by HTTrack Website Copier/3.x [XR&CO'2014], Sat, 09 Sep 2023 12:05:13 GMT -->
<head>
<title>DEALER</title>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge, chrome=1">
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
<meta name="description" content="Lucid Bootstrap 4.1.1 Admin Template">
<meta name="author" content="WrapTheme, design by: ThemeMakker.com">

<link rel="icon" href="{% static 'outgoing-call.png' %}" type="image/x-icon">
<!-- VENDOR CSS -->
<link rel="stylesheet" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'vendor/font-awesome/css/font-awesome.min.css' %}">
<link rel="stylesheet" href="{% static 'vendor/chartist/css/chartist.min.css' %}">
<link rel="stylesheet" href="{% static 'vendor/chartist-plugin-tooltip/chartist-plugin-tooltip.css' %}">
<link rel="stylesheet" href="{% static 'vendor/jvectormap/jquery-jvectormap-2.0.3.min.css' %}"/>
<link rel="stylesheet" href="{% static 'vendor/jquery-datatable/dataTables.bootstrap4.min.css' %}">

<!-- MAIN CSS -->
<link rel="stylesheet" href="{% static 'css/main.css' %}">
<link rel="stylesheet" href="{% static 'css/color_skins.css' %}">
</head>
<body class="theme-cyan" style="background-color:lightcyan;">
  <!-- Page Loader -->
<!-- Overlay For Sidebars -->

<div id="wrapper">

    {% include 'dealer/partials/header.html' %}
    {% include 'dealer/partials/sidebar.html' %}

    {% block content %}

    {% endblock %}

</div>

<!-- Javascript -->
<script src="{% static 'bundles/libscripts.bundle.js' %}"></script>    
<script src="{% static 'bundles/vendorscripts.bundle.js' %}"></script>

<script src="{% static 'bundles/jvectormap.bundle.js' %}"></script> <!-- JVectorMap Plugin Js -->
<script src="{% static 'bundles/chartist.bundle.js' %}"></script>
<script src="{% static 'bundles/datatablescripts.bundle.js' %}"></script>

<script src="{% static 'bundles/mainscripts.bundle.js' %}"></script>
<script src="{% static 'js/pages/tables/jquery-datatable.js' %}"></script>
<script src="{% static 'js/index7.js' %}"></script>

</body>

</html>

templates/dealer/partials/header.html
{% load static %}
  
    
        <nav class="navbar navbar-fixed-top">
            <div class="container-fluid">
                <div class="navbar-btn">
                    <button type="button" class="btn-toggle-offcanvas"><i class="lnr lnr-menu fa fa-bars"></i></button>
                </div>
    
                <div class="navbar-brand">
                    <a href="{% url 'dealer:index' %}"><img src="" class="img-responsive logo"></a>                
                </div>
                
                <div class="navbar-right">
                   
    
                    
                </div>
            </div>
        </nav>
    
        

templates/dealer/partials/sidebar.html
{% load static %}
<div id="left-sidebar" class="sidebar">
    <div class="sidebar-scroll">
        <div class="user-account">
            
            <div class="dropdown">
                <span>Welcome,</span>
                <a href="javascript:void(0);" class="dropdown-toggle user-name" data-toggle="dropdown"><strong>{{request.user}} (Dealer)</strong></a>
                <ul class="dropdown-menu dropdown-menu-right account">
                    <li><a href="{% url 'website:logout' %}"><i class="icon-power"></i>Logout</a></li>
                </ul>
            </div>
            <hr>
          
        </div>
        <!-- Nav tabs -->
      
            
        <!-- Tab panes -->
        <div class="tab-content p-l-0 p-r-0">
            <div class="tab-pane active" id="menu">
                <nav id="left-sidebar-nav" class="sidebar-nav">
                    <ul id="main-menu" class="metismenu">                            
                        <li class="active">
                           
                                <a href="{% url 'dealer:index' %}" ><i class="icon-home"></i> <span>Dashboard</span></a>

                            </li>
                            <li>
                                <a href="{% url 'dealer:sales_report' %}" ><i class="icon-notebook"></i> <span>Sales Report</span></a>
                              
                            </li>
                            <li>
                                <a href="{% url 'dealer:daily_report' %}" ><i class="icon-book-open"></i> <span>Daily Report</span></a>
                              
                            </li>
                        <li>
                            <a href="{% url 'dealer:result' %}" ><i class="icon-trophy"></i> <span>Result</span></a>
                          
                        </li>
                      
                        <li>
                            <a href=" {% url 'dealer:edit_bill_times' %}"><i class="icon-book-open "></i> <span>Edit Bill</span></a>
                         
                        </li>
                        <li>
                            <a href="#uiElements" class="has-arrow"><i class="icon-grid"></i> <span>Reports</span></a>
                            <ul>
                                <li><a href="{% url 'dealer:winning_report' %}">Winning Report</a></li>   

                                <li><a href="{% url 'dealer:count_salereport' %}">Sales Count Report</a></li>

                                <li><a href="{% url 'dealer:winning_countreport' %}">Count Winning Report</a></li> 
                                <li><a href="{% url 'dealer:balance_report' %}">Balance Report</a></li>                             
                              
                           
                            </ul>
                        </li>
                        <li>
                            <a href="{% url 'dealer:change_password' %}" ><i class="icon-wrench"></i> <span>Change Password</span></a>
                           
                        </li>
                        
                       
                     
                    </ul>
                </nav>
            </div>
              
        </div>          
    </div>
</div>